import type { CoverSize, CoverTheme, MainCategory, SkillResource, SkillSubtype } from "./types";

const websiteRepositoryUrl = "https://github.com/NeilBaumanMax/Catnip-Skill-Hub";

interface SeedInput {
  slug: string;
  title: string;
  originalName: string;
  summary: string;
  description: string;
  category: MainCategory;
  tags: readonly string[];
  theme: CoverTheme;
  size: CoverSize;
  subtype?: SkillSubtype;
  features: readonly string[];
  useCases: readonly string[];
  usageSteps: readonly string[];
  promptExamples: readonly string[];
  results: readonly { title: string; description: string }[];
  risks: readonly string[];
  relatedSlugs: readonly string[];
  childSkills?: SkillResource["childSkills"];
  images?: SkillResource["images"];
  galleryTheme?: CoverTheme;
  authorName?: string;
  authorUrl?: string;
  sourceKind?: SkillResource["source"]["kind"];
  repositoryPath?: string;
  repositoryUrl?: string;
  sourceUrl?: string;
  releaseAssetUrl?: string;
  sourceCommit?: string;
  license?: string;
  version?: string;
  downloadEnabled?: boolean;
  sourceLabel?: string;
  adminNotes?: string;
  recommendationWeight?: number;
  pinned?: boolean;
  reviewState?: SkillResource["governance"]["reviewState"];
}

function createSeed(input: SeedInput): SkillResource {
  const subtype = input.subtype ?? "single";
  const repositoryUrl = input.repositoryUrl ?? websiteRepositoryUrl;

  return {
    id: `catnip-${input.slug}`,
    slug: input.slug,
    resourceType: subtype === "single" ? "skill" : "skill_pack",
    subtype,
    title: input.title,
    originalName: input.originalName,
    summary: input.summary,
    description: input.description,
    author: {
      name: input.authorName ?? "Catnip 薄荷猫",
      url: input.authorUrl ?? repositoryUrl,
    },
    source: {
      kind: input.sourceKind ?? (subtype === "editorial_pack" ? "editorial_collection" : "catnip_original"),
      label: input.sourceLabel ?? "Catnip Phase 2 原创演示目录",
      sourceUrl: input.sourceUrl ?? repositoryUrl,
      repositoryUrl,
      repositoryPath: input.repositoryPath,
      releaseAssetUrl: input.releaseAssetUrl,
      license: input.license ?? "待管理员在正式发布前确认",
      version: input.version ?? "0.2.0-demo",
      sourceCommit: input.sourceCommit,
    },
    category: input.category,
    tags: input.tags,
    compatibility: ["Claude Code CLI", "Codex CLI"],
    images: input.images ?? [
      {
        id: `${input.slug}-cover`,
        kind: "cover",
        alt: `${input.title}概念封面`,
        visualKey: input.theme,
        sourceType: "catnip_css",
        sourceLabel: "Catnip Phase 2 CSS 占位视觉",
      },
      ...(input.galleryTheme
        ? [
            {
              id: `${input.slug}-gallery-1`,
              kind: "gallery" as const,
              alt: `${input.title}流程效果示意`,
              visualKey: input.galleryTheme,
              sourceType: "catnip_css" as const,
              sourceLabel: "Catnip Phase 2 CSS 占位视觉",
            },
          ]
        : []),
    ],
    coverTheme: input.theme,
    coverSize: input.size,
    features: input.features,
    useCases: input.useCases,
    childSkills: input.childSkills ?? [],
    usageSteps: input.usageSteps,
    promptExamples: input.promptExamples,
    results: input.results,
    risks: input.risks,
    relatedSlugs: input.relatedSlugs,
    governance: {
      publishStatus: "published",
      inRecommendationPool: true,
      recommendationWeight: input.recommendationWeight ?? 50,
      pinned: input.pinned ?? false,
      hidden: false,
      downloadEnabled: input.downloadEnabled ?? false,
      adminNotes: input.adminNotes ?? "Phase 2 原创演示种子；正式内容接入前不得开放下载。",
      reviewState: input.reviewState ?? "unreviewed",
    },
    stats: {
      views: 0,
      downloadClicks: 0,
      installCopies: 0,
      sourceVisits: 0,
    },
  };
}

export const SKILL_SEEDS: readonly SkillResource[] = [
  createSeed({
    slug: "deeper-reasoning",
    title: "让 Agent 思考得更深",
    originalName: "deeper-reasoning",
    summary: "通过反思、假设检查和多轮推理，减少过早给出浅层答案。",
    description: "为复杂问题建立结构化思考回路，让 Agent 在形成结论前主动检查假设、证据与替代解释。",
    category: "编程开发",
    tags: ["推理增强", "问题分析", "Codex CLI"],
    theme: "mind",
    size: "tall",
    features: ["拆分事实、假设与未知项", "生成替代解释并比较证据", "在输出前执行反思检查"],
    useCases: ["复杂技术方案评估", "难复现缺陷定位", "重要决策的反方检查"],
    usageSteps: ["提供问题、背景与约束", "要求先列假设再推理", "审阅反思结果后确认最终输出"],
    promptExamples: ["分析这个架构选择。先列出隐含假设，再给出至少两个替代方案，最后检查你的结论。"],
    results: [{ title: "更稳健的结论", description: "输出会显式区分证据与推测，方便继续验证。" }],
    risks: ["多轮反思会增加响应时间和上下文消耗", "结构化推理不能替代真实测试或专业审核"],
    relatedSlugs: ["codebase-map", "project-brief"],
    galleryTheme: "map",
  }),
  createSeed({
    slug: "interface-polish",
    title: "把界面细节做到位",
    originalName: "interface-polish",
    summary: "从层级、间距到交互状态，系统检查并改善前端完成度。",
    description: "用一致的审查框架覆盖视觉层级、排版节奏、响应式、键盘操作和状态反馈，帮助产品从能用走向完整。",
    category: "前端设计",
    tags: ["UI 审查", "响应式", "无障碍"],
    theme: "interface",
    size: "medium",
    features: ["检查视觉层级与间距节奏", "覆盖 hover、focus、disabled 等状态", "给出可直接执行的改进清单"],
    useCases: ["上线前界面验收", "设计稿落地复核", "移动端适配检查"],
    usageSteps: ["提供页面目标和现状", "指定重点设备与用户任务", "逐项实施并复核关键状态"],
    promptExamples: ["审查这个页面的层级、间距、键盘焦点和移动端表现，按影响程度排序建议。"],
    results: [{ title: "清晰的改进优先级", description: "把主观的‘不够精致’转化为可验证的问题列表。" }],
    risks: ["仍需在真实浏览器和设备中验证", "不应为了视觉统一牺牲产品任务效率"],
    relatedSlugs: ["design-system", "release-checklist"],
  }),
  createSeed({
    slug: "hardware-prototype",
    title: "快速搭出硬件原型",
    originalName: "hardware-prototype-pack",
    summary: "梳理器件、接线与固件步骤，让 Agent 陪你推进 IoT 原型。",
    description: "把 ESP32 原型从器件清单、接线约束、固件骨架到串口验证整理为连续工作流，适合快速验证硬件创意。",
    category: "VibeCoding 硬件",
    tags: ["ESP32", "IoT", "PlatformIO"],
    theme: "hardware",
    size: "large",
    subtype: "native_pack",
    features: ["生成器件与接口检查表", "组织固件模块和验证顺序", "保留电压、引脚和通信风险提示"],
    useCases: ["ESP32 传感器原型", "小型联网设备验证", "课程与工作坊硬件项目"],
    usageSteps: ["描述主控、器件和目标", "确认电气约束与接线", "分阶段烧录并记录串口结果"],
    promptExamples: ["我要用 ESP32 读取环境传感器并通过 Wi-Fi 上报。先检查器件兼容性，再给出分阶段原型计划。"],
    results: [{ title: "可逐步验证的原型路径", description: "每一步都有输入、预期结果和失败排查入口。" }],
    risks: ["接线前必须独立确认电压、电流和引脚能力", "Agent 输出不能替代数据手册与现场安全措施"],
    relatedSlugs: ["sensor-debug", "release-checklist"],
    childSkills: [
      { id: "esp32-planning", originalName: "esp32-planning", title: "ESP32 原型规划", summary: "整理器件、引脚与里程碑。", hasStandalonePage: false, sourceLabel: "Catnip 原创演示子项" },
      { id: "firmware-scaffold", originalName: "firmware-scaffold", title: "固件骨架生成", summary: "建立可分段验证的固件结构。", hasStandalonePage: false, sourceLabel: "Catnip 原创演示子项" },
      { id: "sensor-debug-child", originalName: "sensor-debug", title: "传感器故障定位", summary: "逐层排查采样链路。", hasStandalonePage: true, standaloneSlug: "sensor-debug", sourceLabel: "Catnip 原创演示子项" },
    ],
    galleryTheme: "sensor",
  }),
  createSeed({
    slug: "project-brief",
    title: "把模糊想法变成清晰任务",
    originalName: "project-brief",
    summary: "从目标、边界到验收标准，生成团队真正能执行的项目简报。",
    description: "通过连续澄清把想法压缩为目标、非目标、受众、约束、里程碑和验收标准，减少开工后的理解偏差。",
    category: "产品与项目管理",
    tags: ["需求拆解", "项目简报", "验收标准"],
    theme: "brief",
    size: "medium",
    features: ["区分目标与非目标", "识别关键依赖和未知项", "生成可测试的验收标准"],
    useCases: ["新功能立项", "跨团队任务交接", "Agent 开发任务说明"],
    usageSteps: ["描述原始想法", "回答关键澄清问题", "确认边界并锁定验收标准"],
    promptExamples: ["把下面的想法整理成项目简报。必须包含非目标、风险和可验证的完成定义。"],
    results: [{ title: "减少返工", description: "团队可以在写代码前发现范围和验收理解差异。" }],
    risks: ["简报质量依赖输入背景是否充分", "重大范围变化需要重新确认而不是静默追加"],
    relatedSlugs: ["release-checklist", "deeper-reasoning"],
    repositoryPath: "content/skills/project-brief",
    repositoryUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main",
    sourceUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main/tree/v0.1.0/content/skills/project-brief",
    releaseAssetUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main/releases/download/v0.1.0/project-brief-0.1.0.zip",
    sourceCommit: "8c594f248d91788abae3938625344d66f349cf1e",
    license: "MIT",
    version: "0.1.0",
    downloadEnabled: true,
    sourceLabel: "Catnip 原创 Skill",
    adminNotes: "Catnip 内容主库 v0.1.0 原创资源；Release workflow 已验证，管理员已显式开放下载。",
  }),
  createSeed({
    slug: "automation-flow",
    title: "让重复工作自己流动",
    originalName: "automation-flow-pack",
    summary: "识别高频步骤并设计可复用的自动化工作流与失败处理。",
    description: "从触发条件、数据流、人工确认点和失败恢复四个角度设计自动化，让效率提升不以失控为代价。",
    category: "自动化",
    tags: ["工作流", "流程设计", "失败恢复"],
    theme: "flow",
    size: "tall",
    subtype: "editorial_pack",
    features: ["识别适合自动化的重复步骤", "定义人工确认与失败回退", "为每个节点记录输入输出"],
    useCases: ["内容整理与分发", "日常研发检查", "跨工具数据搬运"],
    usageSteps: ["列出现有人工流程", "标记风险和不可逆动作", "从只读步骤开始逐步自动化"],
    promptExamples: ["分析这个每周流程，找出可自动化节点，并为每个节点设计失败恢复和人工确认。"],
    results: [{ title: "可控的自动化蓝图", description: "明确哪些动作可以自动执行，哪些必须由人确认。" }],
    risks: ["不可逆外部操作必须保留权限门禁", "上游数据结构变化可能导致流程失效"],
    relatedSlugs: ["research-digest", "release-checklist"],
    childSkills: [
      { id: "workflow-mapping", originalName: "workflow-mapping", title: "工作流映射", summary: "记录触发、节点和输出。", hasStandalonePage: false, sourceLabel: "Catnip 编辑组合演示子项" },
      { id: "failure-recovery", originalName: "failure-recovery", title: "失败恢复设计", summary: "为异常路径定义恢复动作。", hasStandalonePage: false, sourceLabel: "Catnip 编辑组合演示子项" },
      { id: "research-digest-child", originalName: "research-digest", title: "资料行动摘要", summary: "把输入资料整理为行动线索。", hasStandalonePage: true, standaloneSlug: "research-digest", sourceLabel: "Catnip 编辑组合演示子项" },
    ],
    galleryTheme: "release",
  }),
  createSeed({
    slug: "codebase-map",
    title: "先看懂代码，再开始修改",
    originalName: "codebase-map",
    summary: "快速建立代码地图，标记入口、依赖关系与高风险改动区域。",
    description: "在写代码前定位应用入口、领域边界、数据流、关键脚本和质量门禁，为后续修改建立可验证的导航图。",
    category: "编程开发",
    tags: ["代码导航", "架构理解", "影响分析"],
    theme: "map",
    size: "large",
    features: ["识别应用入口和核心路径", "追踪模块依赖与数据流", "标记高风险耦合和验证命令"],
    useCases: ["接手陌生仓库", "大型重构前调查", "缺陷影响范围分析"],
    usageSteps: ["提供仓库目标和当前任务", "读取入口与配置文件", "形成地图后再制定改动计划"],
    promptExamples: ["先不要改代码。请画出这个仓库的入口、主要模块、数据流和测试门禁，并标记与目标功能相关的文件。"],
    results: [{ title: "更小的误改范围", description: "在施工前明确哪些文件必须改、哪些边界应保持不动。" }],
    risks: ["静态阅读可能遗漏运行时行为", "代码地图需要随架构变化及时更新"],
    relatedSlugs: ["deeper-reasoning", "release-checklist"],
    galleryTheme: "mind",
  }),
  createSeed({
    slug: "design-system",
    title: "从零散页面提炼设计系统",
    originalName: "design-system-pack",
    summary: "归纳颜色、字体、组件与状态规则，减少界面越做越乱。",
    description: "从现有界面抽取设计 token、组件构成、交互状态和内容规则，形成可渐进采用的轻量设计系统。",
    category: "前端设计",
    tags: ["Design System", "设计 Token", "组件规范"],
    theme: "system",
    size: "tall",
    subtype: "native_pack",
    features: ["盘点颜色、字体和间距 token", "归纳高频组件及状态", "生成渐进迁移建议"],
    useCases: ["多页面视觉收敛", "前端组件库规划", "设计与研发协作对齐"],
    usageSteps: ["收集代表性页面", "标记重复模式和例外", "先统一高频 token 再收敛组件"],
    promptExamples: ["根据这些页面提取最小设计系统，列出 token、组件、状态和迁移顺序。"],
    results: [{ title: "可持续的界面语言", description: "新页面可以复用规则，而不是继续复制局部样式。" }],
    risks: ["过早追求完整组件库会拖慢产品迭代", "需要保留有业务理由的视觉例外"],
    relatedSlugs: ["interface-polish", "project-brief"],
    childSkills: [
      { id: "token-audit", originalName: "token-audit", title: "设计 Token 盘点", summary: "归纳颜色、排版和间距。", hasStandalonePage: false, sourceLabel: "Catnip 原创演示子项" },
      { id: "component-states", originalName: "component-states", title: "组件状态审查", summary: "覆盖交互与异常状态。", hasStandalonePage: false, sourceLabel: "Catnip 原创演示子项" },
    ],
    galleryTheme: "interface",
  }),
  createSeed({
    slug: "sensor-debug",
    title: "定位传感器的隐形故障",
    originalName: "sensor-debug",
    summary: "按电源、通信、采样和环境因素逐层排查硬件异常。",
    description: "把传感器故障拆成电源、接线、总线、驱动、采样和环境六层，优先使用最小可证伪实验定位根因。",
    category: "VibeCoding 硬件",
    tags: ["传感器", "I2C", "故障排查"],
    theme: "sensor",
    size: "medium",
    features: ["建立分层排查顺序", "设计最小复现实验", "记录读数、环境和固件变量"],
    useCases: ["I2C 设备无响应", "采样漂移和噪声", "间歇性硬件故障"],
    usageSteps: ["记录器件和现象", "从电源与接线开始排除", "每次只改变一个变量"],
    promptExamples: ["这个 I2C 传感器偶发返回零值。请按电源、总线、驱动、采样和环境设计排查实验。"],
    results: [{ title: "可复现的故障证据", description: "将‘偶尔不工作’变成带变量和观察结果的排查记录。" }],
    risks: ["带电测量和接线操作必须遵守硬件安全规范", "不要用软件补偿掩盖尚未定位的电气问题"],
    relatedSlugs: ["hardware-prototype", "deeper-reasoning"],
  }),
  createSeed({
    slug: "release-checklist",
    title: "每次发布都更有把握",
    originalName: "release-checklist",
    summary: "把质量、安全、回滚与沟通整理成可重复执行的发布清单。",
    description: "围绕变更范围、验证结果、数据兼容、权限、安全、回滚和通知建立发布前后检查点。",
    category: "产品与项目管理",
    tags: ["发布管理", "回滚", "质量门禁"],
    theme: "release",
    size: "large",
    features: ["按风险调整发布门禁", "强制记录回滚目标和复测", "覆盖发布前后沟通"],
    useCases: ["Web 应用发布", "配置与依赖升级", "跨团队功能上线"],
    usageSteps: ["列出本次变更和影响范围", "执行对应质量门禁", "确认回滚点后再发布"],
    promptExamples: ["根据这次变更生成发布清单，必须包含安全检查、回滚命令、发布后观察和负责人。"],
    results: [{ title: "可审计的发布记录", description: "后续可以追溯检查、决策、版本和复测结果。" }],
    risks: ["清单不能代替对真实风险的判断", "未经验证的回滚命令不应在生产环境直接使用"],
    relatedSlugs: ["project-brief", "automation-flow"],
    galleryTheme: "brief",
  }),
  createSeed({
    slug: "research-digest",
    title: "把资料整理成行动线索",
    originalName: "research-digest",
    summary: "从分散来源提取观点、证据和待验证问题，形成清晰摘要。",
    description: "把多来源材料整理为结论、证据、分歧、未知项和行动建议，并保留来源线索方便复核。",
    category: "自动化",
    tags: ["信息整理", "研究摘要", "证据追踪"],
    theme: "research",
    size: "tall",
    features: ["区分观点、事实和推断", "合并重复信息并保留分歧", "为行动建议关联证据"],
    useCases: ["技术选型研究", "用户反馈整理", "竞品与趋势资料摘要"],
    usageSteps: ["提供材料与研究问题", "要求逐条保留来源线索", "人工复核关键结论后再行动"],
    promptExamples: ["整理这些资料：先列共识与分歧，再列证据不足的判断，最后给出下一步验证动作。"],
    results: [{ title: "从阅读转向行动", description: "摘要不仅压缩内容，还明确下一步需要验证什么。" }],
    risks: ["摘要可能遗漏来源语境，应保留原文入口", "时效性信息必须在实际使用前重新核验"],
    relatedSlugs: ["automation-flow", "deeper-reasoning"],
  }),
  createSeed({
    slug: "idea-to-production-vibecoding",
    title: "把产品想法安全推进到生产",
    originalName: "idea-to-production-vibecoding",
    summary: "把模糊想法转成产品真相、架构、施工文档、阶段实现与可回滚发布。",
    description: "这是一套面向长周期 VibeCoding 的完整工程治理工作流。它要求 Agent 先发现真实需求并固定产品边界，再建立架构和施工文档，检查 Git 与用户改动，按 Phase 实现、测试、截图验收和记录失败，最后留下下一位 Agent 可以无聊天记录接力的交接材料。",
    category: "产品与项目管理",
    tags: ["VibeCoding", "产品规划", "工程治理", "Codex CLI"],
    theme: "flow",
    size: "large",
    authorName: "Neil Bauman / Catnip 薄荷猫",
    authorUrl: "https://github.com/NeilBaumanMax/idea-to-production-vibecoding",
    sourceKind: "catnip_original",
    sourceLabel: "Neil Bauman / Catnip 原创 Skill",
    sourceUrl: "https://github.com/NeilBaumanMax/idea-to-production-vibecoding/tree/1ed2eb67325716f65deaee3bf7fcc8b7d998c282",
    repositoryUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main",
    repositoryPath: "content/skills/idea-to-production-vibecoding",
    releaseAssetUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main/releases/download/v0.2.0/idea-to-production-vibecoding-1.0.0.zip",
    sourceCommit: "1ed2eb67325716f65deaee3bf7fcc8b7d998c282",
    license: "MIT",
    version: "1.0.0",
    downloadEnabled: true,
    recommendationWeight: 92,
    pinned: true,
    reviewState: "reviewed",
    adminNotes: "Catnip 内容主库 v0.2.0；Release workflow、SHA-256 与 ZIP 完整性已验证。",
    images: [
      {
        id: "idea-to-production-vibecoding-cover",
        kind: "cover",
        alt: "从想法、架构、代码与测试门禁通向生产发布的三维流程封面",
        url: "/skills/idea-to-production-vibecoding/cover.jpg",
        visualKey: "flow",
        sourceType: "ai_generated",
        sourceLabel: "Catnip AI 生成视觉",
      },
      {
        id: "idea-to-production-vibecoding-gallery-1",
        kind: "gallery",
        alt: "从需求发现到生产交付的六阶段工程流程示意",
        url: "/skills/idea-to-production-vibecoding/effect.png",
        visualKey: "map",
        sourceType: "ai_generated",
        sourceLabel: "Catnip AI 生成视觉",
      },
    ],
    features: [
      "通过访谈式澄清区分产品事实、假设、未知项与非目标",
      "建立架构、产品要求、施工计划、测试指标和回滚手册",
      "开工前识别用户改动并创建可验证的远端备份",
      "按 Phase 施工，记录失败测试、修复、复测和文档漂移",
      "为下一位 Agent 输出无需聊天记录即可接力的交接材料",
    ],
    useCases: ["从零启动一个 Agent 驱动产品", "接管已经混乱的 VibeCoding 仓库", "长周期、多轮 Codex CLI 开发", "需要审计、回滚和持续交接的生产项目"],
    usageSteps: [
      "把产品想法、目标用户和当前仓库状态交给 Agent。",
      "完成需求发现，确认目标、非目标、风险和验收定义。",
      "让 Agent 建立施工文档、Git 基线与开发前远端备份。",
      "按 Phase 实现，每轮执行测试、截图或运行验证并记录失败。",
      "审核交接与回滚信息，确认门禁通过后再发布。",
    ],
    promptExamples: [
      "使用 idea-to-production-vibecoding，把这个产品想法从需求发现推进到可施工计划。先不要写代码，先固定产品真相、非目标和验收标准。",
      "接管这个仓库。保护用户改动，建立开发前备份，然后按现有 Phase 文档继续施工、测试和交接。",
    ],
    results: [
      { title: "范围更稳定", description: "把聊天里的模糊愿望压缩为可追踪的产品边界与完成定义。" },
      { title: "施工可审计", description: "提交、测试、失败、备份和回滚目标形成连续证据链。" },
      { title: "跨会话可接力", description: "后续 Agent 不依赖旧聊天也能恢复上下文并继续工作。" },
    ],
    risks: ["完整治理会增加前期整理与验证时间，不适合一次性小脚本", "文档与检查清单不能替代真实运行测试、专业安全审核或用户验收"],
    relatedSlugs: ["project-brief", "codebase-map", "release-checklist"],
  }),
  createSeed({
    slug: "apple-design",
    title: "让界面拥有流体般的自然反馈",
    originalName: "apple-design",
    summary: "把空间连续性、弹簧、手势、动量与可中断动画转译为可落地的 Web 交互。",
    description: "这套 Skill 总结了 Emil Kowalski 对 Apple 式界面物理感的工程化理解：界面元素从哪里来、如何响应按压与拖拽、松手后怎样保留速度、动画被打断时如何继续，以及何时应为减少动态效果的用户降级。它提供的是设计原则与 Web 实现方法，不复制任何 Apple 产品或商标。",
    category: "前端设计",
    tags: ["动效设计", "手势交互", "Spring", "Web UI"],
    theme: "interface",
    size: "large",
    authorName: "Emil Kowalski",
    authorUrl: "https://github.com/NeilBaumanMax/Apple_Design_SKILL",
    sourceKind: "third_party",
    sourceLabel: "Emil Kowalski 原作，经 Catnip 整理发布",
    sourceUrl: "https://github.com/NeilBaumanMax/Apple_Design_SKILL/tree/6bf24434f7730ad169077756cf9c7cd7bd675fc6/skills/apple-design",
    repositoryUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main",
    repositoryPath: "content/skills/apple-design",
    releaseAssetUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main/releases/download/v0.2.0/apple-design-1.0.0.zip",
    sourceCommit: "6bf24434f7730ad169077756cf9c7cd7bd675fc6",
    license: "MIT",
    version: "1.0.0",
    downloadEnabled: true,
    recommendationWeight: 88,
    pinned: true,
    reviewState: "reviewed",
    adminNotes: "Catnip 内容主库 v0.2.0；保留原作者与 MIT License，视觉未使用 Apple 标志。",
    images: [
      {
        id: "apple-design-cover",
        kind: "cover",
        alt: "半透明界面层与弹簧运动轨迹组成的流体交互封面",
        url: "/skills/apple-design/cover.jpg",
        visualKey: "interface",
        sourceType: "ai_generated",
        sourceLabel: "Catnip AI 生成视觉（无 Apple 标志）",
      },
      {
        id: "apple-design-gallery-1",
        kind: "gallery",
        alt: "按压、拖拽、动量与可中断弹簧四种交互状态示意",
        url: "/skills/apple-design/effect.png",
        visualKey: "interface",
        sourceType: "ai_generated",
        sourceLabel: "Catnip AI 生成视觉（无 Apple 标志）",
      },
    ],
    features: [
      "用空间连续性解释弹层、卡片和导航元素的来源与去向",
      "为 press、drag、release 和 momentum 选择合适的反馈模型",
      "设计带初速度、可中断且不会跳变的弹簧动画",
      "控制模糊、缩放、透明度和阴影，避免过度装饰",
      "同时考虑 reduced motion、触控与键盘用户",
    ],
    useCases: ["手势驱动的卡片与面板", "移动端风格的 Web 导航", "高完成度弹窗和浮层", "审查已有动画是否自然且可访问"],
    usageSteps: [
      "描述用户动作、界面元素的空间关系和现有技术栈。",
      "判断反馈应使用即时状态、补间动画还是物理弹簧。",
      "明确持续时间、阻尼、初速度、中断行为和降级策略。",
      "在鼠标、触控、键盘及 reduced motion 下分别验证。",
    ],
    promptExamples: [
      "使用 apple-design 审查这个抽屉交互：它应从触发按钮所在空间自然展开，拖拽松手后保留速度，并能在反向操作时立即中断。",
      "把这个生硬的弹窗改成克制的物理反馈，同时给出 prefers-reduced-motion 的降级方案。",
    ],
    results: [
      { title: "动作有因果", description: "用户能从运动方向和连续性理解界面发生了什么。" },
      { title: "交互可打断", description: "快速连续操作不会等待旧动画结束，也不会出现跳帧。" },
      { title: "精致但克制", description: "动效服务于反馈和空间理解，而不是单纯展示技巧。" },
    ],
    risks: ["该 Skill 是面向 Web 的设计方法总结，不代表 Apple 官方规范或授权", "必须测试 prefers-reduced-motion；高频模糊和大面积动画可能影响性能与可访问性"],
    relatedSlugs: ["interface-polish", "design-system"],
  }),
  createSeed({
    slug: "dashi-ppt",
    title: "生成可编辑、可导出的专业演示",
    originalName: "dashi-ppt",
    summary: "从内容结构到 HTML 预览、PDF 与 PPTX 导出，完成可继续编辑的专业演示文稿。",
    description: "Dashi PPT Skill 提供一套完整的演示文稿生产系统：先组织故事与页面角色，再从 12 套主题和约 1020 种布局中选择结构，生成可编辑的 HTML 演示，执行视觉预览与质量检查，并按需要导出 PDF 或 PPTX。内容包保留原项目和导出组件的许可证边界，适合真正需要交付文件的 Agent 工作流。",
    category: "自动化",
    tags: ["PPT", "演示文稿", "PPTX", "PDF"],
    theme: "release",
    size: "large",
    authorName: "chuspeeism",
    authorUrl: "https://github.com/NeilBaumanMax/dashi-ppt-skill-ZYY--Neil",
    sourceKind: "third_party",
    sourceLabel: "chuspeeism 原作，经 Catnip 完整镜像发布",
    sourceUrl: "https://github.com/NeilBaumanMax/dashi-ppt-skill-ZYY--Neil/tree/fdbb145517ea0e289000aef9b7906bcb3e0cd19a/skills/dashi-ppt",
    repositoryUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main",
    repositoryPath: "content/skills/dashi-ppt",
    releaseAssetUrl: "https://github.com/neilbauman666/Catnip-skill-hub-main/releases/download/v0.2.0/dashi-ppt-0.4.4.zip",
    sourceCommit: "fdbb145517ea0e289000aef9b7906bcb3e0cd19a",
    license: "AGPL-3.0（内含仅限随完整 Skill 使用和分发的专有导出组件）",
    version: "0.4.4",
    downloadEnabled: true,
    recommendationWeight: 94,
    pinned: true,
    reviewState: "reviewed",
    adminNotes: "Catnip 内容主库 v0.2.0 完整分发；不得单独提取 html-deck-to-pptx 专有组件。",
    images: [
      {
        id: "dashi-ppt-cover",
        kind: "cover",
        alt: "浮动演示页面、编辑画布、图表和导出控件组成的专业演示封面",
        url: "/skills/dashi-ppt/cover.jpg",
        visualKey: "release",
        sourceType: "ai_generated",
        sourceLabel: "Catnip AI 生成视觉",
      },
      {
        id: "dashi-ppt-gallery-1",
        kind: "gallery",
        alt: "Dashi PPT 原项目主题与版式效果网格",
        url: "/skills/dashi-ppt/effect.png",
        visualKey: "system",
        sourceType: "original_author",
        sourceLabel: "Dashi PPT 原项目效果图",
      },
    ],
    features: [
      "按受众、目的和叙事节奏规划整套演示结构",
      "提供 12 套主题与约 1020 种版式组合",
      "生成可在浏览器继续编辑和预览的 HTML 演示",
      "执行页面渲染、拼图预览、溢出和视觉质量检查",
      "导出 PDF 与可继续编辑的 PPTX 文件",
    ],
    useCases: ["商业方案与路演 Deck", "课程、培训和知识分享", "研究报告与项目汇报", "需要 PDF/PPTX 成品的 Agent 自动化"],
    usageSteps: [
      "确认本机具备 Node.js 20+；首次安装依赖和浏览器组件可能需要联网。",
      "描述受众、演示目标、页数、语言、资料与品牌约束。",
      "让 Skill 规划页面角色并选择主题与版式。",
      "生成 HTML 后运行预览与质量检查，修正文字溢出和视觉问题。",
      "确认效果后导出 PDF 或 PPTX，并在目标软件中复核可编辑性。",
    ],
    promptExamples: [
      "使用 dashi-ppt，把这些产品资料做成 12 页中文融资路演。先给出故事线和页面角色，再生成可编辑 HTML，截图检查后导出 PPTX。",
      "把这份研究报告压缩为 8 页高管汇报，使用克制的数据叙事，避免每页重复同一种版式，最终同时输出 PDF 和 PPTX。",
    ],
    results: [
      { title: "从内容到成品", description: "不止提供提纲，还覆盖排版、预览、检查与文件导出。" },
      { title: "版式更丰富", description: "主题和布局系统减少模板化、重复化的页面观感。" },
      { title: "文件可继续编辑", description: "HTML 与 PPTX 交付后仍可由团队进行二次修改。" },
    ],
    risks: ["完整 Skill 体积约 25.6 MB，安装依赖和浏览器组件需要额外磁盘、时间与可能的网络访问", "主项目采用 AGPL-3.0；html-deck-to-pptx 专有组件只能随完整 Dashi Skill 使用和分发，不得单独提取或再分发"],
    relatedSlugs: ["research-digest", "automation-flow", "project-brief"],
  }),
];

const REQUIRED_PUBLIC_SKILL_SLUGS = new Set([
  "idea-to-production-vibecoding",
  "apple-design",
  "dashi-ppt",
]);

export const REQUIRED_PUBLIC_SKILL_SEEDS: readonly SkillResource[] = SKILL_SEEDS.filter(
  (skill) => REQUIRED_PUBLIC_SKILL_SLUGS.has(skill.slug),
);
